name: Deploy playground to Github Pages

on:
  push:
    branches: [main, github-pages]

defaults:
  run:
    working-directory: ./examples/scrollbar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      # - uses: jetli/wasm-pack-action@v0.3.0
      #   with:
      #     version: latest

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install
        run: npm install

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: npm run build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
